### ISSUE TITLE
全局安装 执行sparrow 无法启动 

### ISSUE THREAD

**Issue by yanjizhou** [sparrow-js/sparrow#35]
![image](https://user-images.githubusercontent.com/34884637/133870060-90c8981e-db9f-4cc9-86b9-82edb7014cac.png)

**Comment by BestErwin** [comment]
我也是这个错误启动不了，啥问题啊

**Comment by sparrow-js** [comment]
1.查看node版本，v11以上
2.检测项目安装情况:cd ~/.sparrow/sparrow-server/ 主界面服务，cd ~/.sparrow/sparrow-view 预览服务
3.在2的目录里手动运行，看看是否报错

**Comment by songyi1999** [comment]
同样启动不了.
`npm run  sparrow

> lowcode@1.0.0 sparrow
> sparrow start -m page

sparrow view Core: 0.1.0 C:\Users\songyi\.sparrow\sparrow-server
sparrow view Core: 0.4.3 C:\Users\songyi\.sparrow\sparrow-server
sparrow Core: 0.9.27 C:\Users\songyi\.sparrow\sparrow-server
ϵͳ�Ҳ���ָ����·����


😞  Start sparrow failed

Error: spawn C:\Users\songyi\.sparrow\sparrow-server\node_modules\.bin\egg-scripts ENOENT
    at notFoundError (D:\lowcode\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:6:26)    
    at verifyENOENT (D:\lowcode\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:40:16)    
    at ChildProcess.cp.emit (D:\lowcode\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\Users\\songyi\\.sparrow\\sparrow-server\\node_modules\\.bin\\egg-scripts',    
  path: 'C:\\Users\\songyi\\.sparrow\\sparrow-server\\node_modules\\.bin\\egg-scripts',
  spawnargs: [
    'start',
    '--title=sparrow-server',
    '--framework=midway-mirror',
    '--workers=1',
    '--sticky',
    '--project=D:\\lowcode'
  ]
}`

**Comment by sparrow-js** [comment]
进入：cd ~/.sparrow/sparrow-server/ 主界面服务，cd ~/.sparrow/sparrow-view 预览服务
手动npm install 下依赖，然后在运行

**Comment by HaomengYu1** [comment]
试过了，还是启动不起来
