### ISSUE TITLE
项目内安装，运行报错，请问能帮忙解决一下吗

### ISSUE THREAD

**Issue by LiuJing1014** [sparrow-js/sparrow#43]
PS C:\Users\Administrator\Desktop\sparrow-demo> npm run sparrow

> sparrow-demo@0.1.0 sparrow
> sparrow start -m page     

sparrow view Core: 0.1.0 C:\Users\Administrator\.sparrow\sparrow-server
sparrow view Core: 0.4.3 C:\Users\Administrator\.sparrow\sparrow-server
sparrow Core: 0.9.27 C:\Users\Administrator\.sparrow\sparrow-server
ϵͳ�Ҳ���ָ����·����

😞  Start sparrow failed

Error: spawn C:\Users\Administrator\.sparrow\sparrow-server\node_modules\.bin\egg-scripts ENOENT
    at notFoundError (C:\Users\Administrator\Desktop\sparrow-demo\node_modules\sparrow-code\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\Administrator\Desktop\sparrow-demo\node_modules\sparrow-code\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\Administrator\Desktop\sparrow-demo\node_modules\sparrow-code\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\Users\\Administrator\\.sparrow\\sparrow-server\\node_modules\\.bin\\egg-scripts',
  path: 'C:\\Users\\Administrator\\.sparrow\\sparrow-server\\node_modules\\.bin\\egg-scripts',
  spawnargs: [
    'start',
    '--title=sparrow-server',
    '--framework=midway-mirror',
    '--workers=1',
    '--sticky',
    '--project=C:\\Users\\Administrator\\Desktop\\sparrow-demo'
  ]
}
PS C:\Users\Administrator\Desktop\sparrow-demo>

**Comment by mlinge** [comment]
进入 C:\Users\Administrator\Desktop\sparrow-demo 目录，再单独npm i --force，然后再启动
